services:
  onboard:
    build:
      context: ./
      dockerfile: Onboard.Dockerfile
    
    image: roboracer_stack:onboard
    # ipc: host
    ports:
      - "8765:8765"
  devkit:
    image: "dheeshik/roboracer_neu:devkit"
    pull_policy: always
    # ipc: host
    privileged: true
    ports:
      - "4567:4567"
    