services:
  onboard:
    image: "dheeshik/roboracer_neu:onboard"
    # ipc: host
    ports:
      - "8765:8765"
  sim_api:
    image: "dheeshik/roboracer_neu:devkit"
    # ipc: host
    privileged: true
    ports:
      - "4567:4567"
    